poll/urls.py
from django.urls import path,include
from poll import views
from rest_framework.routers import DefaultRouter

app_name="poll"

router=DefaultRouter()
router.register('api/polls',views.PollViewSet,)

urlpatterns = [
    path('',views.polls,name="polls"),
    path('add/',views.add_poll,name="add"),
    
    path('details/',include([
        path('<int:poll_id>/',views.poll_detail,name="details"),
        path('<int:poll_id>/vote/',views.poll_vote,name="vote")
    ])),
    
    path('edit/',include([
        path('poll/<int:poll_id>',views.edit_poll,name="edit_poll"),
        path('<int:poll_id>/choice/add/',views.add_choice,name="add_choice"),
        path('choice/<int:choice_id>',views.edit_choice,name="edit_choice"),
    ])),
    
    path('delete/',include([
        path('choice/<int:choice_id>',views.delete_choice,name="delete_choice"),
        path('poll/<int:poll_id>/',views.delete_poll,name="delete_poll"),
    ])),
    
    # API VIEWS starts
    path('api/',include([
        path('users',views.Users.as_view(),name="users"),
        path('login',views.LoginView.as_view(),name="api_login"),
        path('polls/', include([
            # path('',views.PollList2.as_view(),name="polls_list"),
            # path('<int:pk>',views.PollDetail2.as_view(),name="poll_detail"),
            path('<int:poll_pk>/choices',views.ChoiceList.as_view(),name="choice_list"),
            path('<int:poll_pk>/choices/<int:choice_pk>/vote',views.CreateVote.as_view(),name="create_vote"),
        ]))
    ]))
]

# adds url paths for polls list,create and details views
# first arg on register func tacks on to the app's default url i.e  127.0.0.1:8000/<app_name>/<first_arg>/
# and use base_name for path name ie poll-list,poll-details
urlpatterns+= router.urls 

pollme/urls.py
from django.contrib import admin
from django.urls import path,include
from pollme import views
# from rest_framework_swagger.views import get_swagger_view
from rest_framework.documentation import include_docs_urls
# schema_view = get_swagger_view(title='Polls API')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name="home"),
    path('poll/',include('poll.urls',namespace="poll")),
    path('accounts/',include('accounts.urls',namespace="accounts")),
    # path('swagger-docs/', schema_view),
    path('docs/', include_docs_urls(title='M\'s simple Polls API Build')),
]

poll/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Poll(models.Model):
    owner=models.ForeignKey(User, on_delete=models.CASCADE,default=1)
    text = models.CharField(max_length=200)
    pub_date = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Poll"
        verbose_name_plural = "Polls"

    def __str__(self):
        return self.text
    
    def user_can_vote(self,user):
        """
        Returns True if user can vote, else returns False
        """
        user_votes=user.vote_set.all()
        qs=user_votes.filter(poll=self)
        if qs.exists():
            return False
        return True
    
    def num_votes(self):
        """
        Returns the number of votes on a poll
        """
        return self.vote_set.count()

        
    
class Choice(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200) 

    def __str__(self):
        return self.choice_text
    def num_votes(self):
        """
        Returns the number of votes on a particular choice
        """
        return self.vote_set.count()


class Vote(models.Model):
    poll=models.ForeignKey(Poll,on_delete=models.CASCADE)
    choice=models.ForeignKey(Choice,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)

poll/forms.py
from django import forms
from poll.models import Poll,Choice

class PollForm(forms.ModelForm):
    choice1=forms.CharField(
                                label="First Choice", 
                                required=True,
                                widget=forms.TextInput(
                                    attrs={'class':'form-control'}
                                    )
                            )
    choice2=forms.CharField(
                                label="Second Choice", 
                                required=True,
                                widget=forms.TextInput(
                                    attrs={'class':'form-control'}
                                    )
                            )
    class Meta:
        model = Poll
        fields = ['text','choice1','choice2']
        widgets={
            'text':forms.Textarea(attrs={'class':'form-control','rows':5,'cols':20})
        }

class EditPollForm(forms.ModelForm):
    class Meta:
        model = Poll
        fields = ['text']
        widgets={
            'text':forms.Textarea(attrs={'class':'form-control','rows':5,'cols':20})
        }

class ChoiceForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ['choice_text']
    

poll/views.py
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import render,get_object_or_404,redirect
from poll.models import Poll,Choice,Vote,User
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from poll.forms import PollForm,EditPollForm,ChoiceForm
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger

# API views
from .serializers import UserSerializer,VoteSerializer,PollSerializer,ChoiceSerializer
# from django.http import HttpResponse
# from django.views.decorators.csrf import csrf_exempt  #allows csrf from any origin
# from rest_framework.parsers import JSONParser
# from rest_framework.renderers import JSONRenderer
from django.contrib.auth import authenticate
from rest_framework import status
from rest_framework.views import APIView
from rest_framework import generics
from rest_framework.response import Response
from rest_framework import viewsets
from rest_framework.exceptions import PermissionDenied
# Create your views here.


# API funcs starts
# Versions of API in acsending order
# comment out all but one at an instance 
# edit urls.py to match the uncommented view 
# and import neccessary modules

# Version 1

# class JSONResponse(HttpResponse):
#     def __init__(self, data, **kwargs):
#         content = JSONRenderer().render(data)
#         kwargs['content_type'] = 'application/json'
#         super(JSONResponse, self).__init__(content, **kwargs)

# @csrf_exempt
# def user_list(request):
#     if request.method == 'GET':
#         users = User.objects.all()
#         users_serializer = UserSerializer(users, many=True)
#         return JSONResponse(users_serializer.data)
    
#     elif request.method == 'POST':
#         user_data = JSONParser().parse(request)
#         user_serializer = UserSerializer(data=user_data)
#         if user_serializer.is_valid():
#             user_serializer.save()
#             return JSONResponse(user_serializer.data, status=status.HTTP_201_CREATED)
#         return JSONResponse(user_serializer.errors,status=status.HTTP_400_BAD_REQUEST)


# class PollList(APIView):
#     def get(self,request):
#         polls=Poll.objects.all()
#         data=PollSerializer(polls,many=True).data
#         return JSONResponse(data)

# class PollDetail(APIView):
#     def get(self,request,pk):
#         poll=get_object_or_404(Poll,pk=pk)
#         data=PollSerializer(poll).data
#         return JSONResponse(data)

# version 2
class Users(generics.ListCreateAPIView):
    authentication_classes=()
    permission_classes=()
    queryset=User.objects.all()
    serializer_class=UserSerializer

# PollList2 and PollDetail2 has been replaced with PollViewSet class

# class PollList2(generics.ListCreateAPIView):
#     queryset=Poll.objects.all()
#     serializer_class=PollSerializer

# class PollDetail2(generics.RetrieveDestroyAPIView):
#     queryset=Poll.objects.all()
#     serializer_class=PollSerializer

class ChoiceList(generics.ListCreateAPIView):
    def get_queryset(self):
        queryset=Choice.objects.filter(poll_id=self.kwargs['poll_pk'])
        return queryset
    serializer_class=ChoiceSerializer

    # prevents authenticated user from posting choice to polls they didn't create
    def post(self,request,*args, **kwargs):
        poll=Poll.objects.get(pk=self.kwargs['poll_pk'])
        if not request.user == poll.owner:
            raise PermissionDenied("You can not create choice for this poll.")
        return super().post(request,* args, ** kwargs)



class ChoiceDetail(generics.RetrieveDestroyAPIView):
    queryset=Choice.objects.all()
    serializer_class=ChoiceSerializer

class CreateVote(generics.CreateAPIView):
    serializer_class=VoteSerializer
    def post(self,request,poll_pk,choice_pk):
        voted_by=request.data.get('user')
        data={'poll':poll_pk,'choice':choice_pk,'user':voted_by}
        serializer=VoteSerializer(data=data)
        if serializer.is_valid():
            vote=serializer.save()
            return Response(serializer.data,status=status.HTTP_201_CREATED)
        else:
            return Response(serializer.errors,status=status.HTTP_400_BAD_REQUEST)

class PollViewSet(viewsets.ModelViewSet):
    queryset=Poll.objects.all()
    serializer_class=PollSerializer

    # prevents authenticated user from deleting polls he didn't create
    def destroy(self, request,* args, ** kwargs):
        poll = Poll.objects.get(pk=self.kwargs["pk"])
        if not request.user == poll.owner:
            raise PermissionDenied("You can not delete this polls you didn't create.")
        return super().destroy(request,* args, ** kwargs)

class LoginView(APIView):
    permission_classes = ()
    def post(self, request,):
        username = request.data.get("username")
        password = request.data.get("password")
        user = authenticate(username=username, password=password)
        if user:
            return Response({"token": user.auth_token.key})
        else:
            return Response({"error": "Wrong Credentials"}, status=status.HTTP_400_BAD_REQUEST)

# API func ends


@login_required
def polls(request):
    polls=Poll.objects.all()
    search_keyword=''

    if 'title' in request.GET:
        polls=polls.order_by('text')
    if 'latest' in request.GET:
        polls=polls.order_by('-pub_date')
    if 'mine' in request.GET:
        polls=request.user.poll_set.all().order_by('text')
    if 'search' in request.GET:
        search_keyword=request.GET['search']
        polls=polls.filter(text__icontains=search_keyword)
    
    get_dict_copy=request.GET.copy()
    params=get_dict_copy.pop('page',True) and get_dict_copy.urlencode()

    
    paginator=Paginator(polls,3)
    page=request.GET.get('page')
    polls=paginator.get_page(page)

    context={
        'polls':polls,
        'params':params,
        'search':search_keyword,
    }
    return render(request,'poll/polls.html',context)

@login_required
def add_poll(request):
    if request.method=="POST":
        form=PollForm(request.POST)
        if form.is_valid():
            new_poll=form.save(commit=False)
            new_poll.owner=request.user
            new_poll.save()
            new_choice1=Choice(poll=new_poll,choice_text=form.cleaned_data['choice1']).save()
            new_choice2=Choice(poll=new_poll,choice_text=form.cleaned_data['choice2']).save()
            messages.success(request,"Poll and Choices added successfully",extra_tags='alert alert-success alert-dismissible fade show')
            return redirect('poll:polls')
    else:
        form = PollForm()

    context={
        'form':form 
    }
    return render(request,'poll/add_poll.html',context)

@login_required
def edit_poll(request,poll_id):
    poll=get_object_or_404(Poll,id=poll_id)
    if request.user!=poll.owner:
        return HttpResponse("You're not authorized to view this page")
    
    if request.method=="POST":
        form=EditPollForm(request.POST,instance=poll)
        if form.is_valid():
            form.save()
            messages.success(request,"Poll edit successful",extra_tags='alert alert-success alert-dismissible fade show')
            return redirect('poll:polls')
    else:
        form=EditPollForm(instance=poll)
        
    context={
        'poll':poll,
        'form':form
    }
    return render(request,'poll/edit_poll.html',context)

@login_required
def add_choice(request,poll_id):
    poll=get_object_or_404(Poll,id=poll_id)
    if request.user!=poll.owner:
        return HttpResponse("You're not authorized to view this page")
    
    if request.method=="POST":
        form=ChoiceForm(request.POST)
        if form.is_valid():
            new_choice=form.save(commit=False)
            new_choice.poll=poll
            new_choice.save()
            messages.success(request,"Choice added successfully",extra_tags='alert alert-success alert-dismissible fade show')
            return redirect(reverse('poll:details',kwargs={'poll_id':poll_id}))
    else:
        form=ChoiceForm()
        
    context={
        'poll':poll,
        'form':form
    }
    return render(request,'poll/add_choice.html',context)

@login_required
def edit_choice(request,choice_id):
    choice=get_object_or_404(Choice,id=choice_id)
    if request.user!=choice.poll.owner:
        return HttpResponse("You're not authorized to make changes to this choice")
    
    if request.method=="POST":
        form=ChoiceForm(request.POST,instance=choice)
        if form.is_valid():
            
            form.save()
            messages.success(request,"Choice edited successfully",extra_tags='alert alert-success alert-dismissible fade show')
            return redirect(reverse('poll:edit_poll',kwargs={'poll_id':choice.poll.id}))
    else:
        form=ChoiceForm(instance=choice)

    context={
        'form':form,
        'choice':choice
    }
    return render(request,'poll/edit_choice.html',context)

@login_required
def delete_choice(request,choice_id):
    choice=get_object_or_404(Choice,id=choice_id)
    if request.method=='POST':
        choice.delete()
        messages.success(request,"Choice deleted successfully",extra_tags='alert alert-success alert-dismissible fade show')
        return redirect(reverse('poll:edit_poll',kwargs={'poll_id':choice.poll.id}))
        
    context={
        'choice':choice,
        'poll':False
    }
    return render(request,'poll/confirm_delete.html',context)

@login_required
def delete_poll(request,poll_id):
    poll=get_object_or_404(Poll,id=poll_id)
    if request.method=='POST':
        poll.delete()
        messages.success(request,"Poll deleted successfully",extra_tags='alert alert-success alert-dismissible fade show')
        return redirect('poll:polls')
        
    context={
        'choice':False,
        'poll':poll
    }
    return render(request,'poll/confirm_delete.html',context)

@login_required
def poll_detail(request,poll_id):
    poll=get_object_or_404(Poll,id=poll_id)

poll/templates/poll/add_choice.html
{% extends 'base.html' %}
{% block css %}

{% endblock css %}
{% block content %}
<div class="container">
<h1 class="text-center">Current Poll: {{poll.text}} </h1>
<p class="text-center">Add choice to current poll with the form below </p>
<form class="" action="" method="post">
    {{form.non_field_errors}}
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group">
        {{field.errors}}
        {{field.label_tag}}
        {{field}}
        
    </div>
    {% endfor %}
    <input class="btn btn-primary" type="submit" value="Add choice"> 

</form>
</div>
{% endblock content %}

poll/templates/poll/add_poll.html
{% extends 'base.html' %}
{% block css %}

{% endblock css %}
{% block content %}
<div class="container">
<h1 class="text-center">Add polls with the form below </h1>
<form class="" action="" method="post">
    {{form.non_field_errors}}
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group">
        {{field.errors}}
        {{field.label_tag}}
        {{field}}
        
    </div>
    {% endfor %}
    <input class="btn btn-primary" type="submit" value="Submit">

</form>
</div>
{% endblock content %}

poll/templates/poll/confirm_delete.html
{% extends 'base.html' %}
{% block font_css %} {% endblock font_css %}
{% block title %} edit choice {% endblock title %}
{% block content %}
<div class="container">
    <h1>You're trying to delete 
    {% if poll %}    
        poll: {{poll.text}}
    {% else %}
        choice: {{choice.choice_text}}</h1>
    {% endif %}
    <form class="" action="" method="post">
    {% csrf_token %} 
    <input class="btn btn-danger" type="submit" value="Confirm {% if poll %}poll{% else %}choice{% endif %} delete">
    </form>
</div>


{% endblock content %}

poll/templates/poll/edit_choice.html
{% extends 'base.html' %}
{% block font_css %} {% endblock font_css %}
{% block title %} edit choice {% endblock title %}
{% block content %}
<div class="container">
    <h1>You're trying to edit: {{choice.choice_text}}</h1>
    <form class="" action="" method="post">
    {{form.non_field_errors}}
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group">
        {{field.errors}}
        {{field.label_tag}}
        {{field}}
        
    </div>
    {% endfor %}
    <input class="btn btn-primary" type="submit" value="Edit choice">
    </form>
</div>


{% endblock content %}

poll/templates/poll/edit_poll.html
{% extends 'base.html' %}
{% block font_css %} {% endblock font_css %}
{% block title %} edit poll {% endblock title %}
{% block content %}
<div class="container">
    <h1>You're trying to edit: {{poll}}</h1>
    <form class="" action="" method="post">
    {{form.non_field_errors}}
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group">
        {{field.errors}}
        {{field.label_tag}}
        {{field}}
        
    </div>
    {% endfor %}
    <input class="btn btn-primary" type="submit" value="Submit">
    <a href="{% url 'poll:add_choice' poll.id %}" class="btn btn-warning"> Add choices </a>
    <a href="{% url 'poll:delete_poll' poll.id %}" class="btn btn-danger"> Delete Poll</a>
    </form><br><br>
    <div class="col-md-6 offset-md-3">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %} 
                <li {% if message.tags %} class="{{message.tags}}" {% endif %}>
                    {{message}}

                </li>
            {% endfor %}
        </ul>
    {% endif %}
        {% for choice in poll.choice_set.all %}
            <p>
                <a href="{% url 'poll:edit_choice' choice.id %}">Edit</a>
                {{choice.choice_text}}
                <a href="{% url 'poll:delete_choice' choice.id %}">Delete</a> 
            </p>
        {% endfor %}
    </div>
</div>


{% endblock content %}

poll/templates/poll/poll_details.html
{% extends 'base.html' %}
{% block title %} {% endblock %}
{% block content %}
<div class="container">
    {% comment  %} <a href="{% url 'poll:delete' %}">Delete poll</a>{% endcomment %}
    {% if messages %}
        <ul class="messages">
            {% for message in messages %} 
                <li {% if message.tags %} class="{{message.tags}}" {% endif %}>
                    {{message}}

                </li>
            {% endfor %}
        </ul>
    {% endif %}

    <form action="{% url 'poll:vote' poll.id %}" method="post">
        {% csrf_token %}
        {% for choice in poll.choice_set.all %}
        <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
        <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label>
        <br>
        {% endfor %}
        <input class="btn btn-primary" type="submit" value="Submit" {% if not user_can_vote %} disabled {% endif %} >    
    </form>
</div>

{% endblock %}

poll/templates/poll/poll_results.html
{% extends 'base.html' %}
{% block title %} {% endblock %}
{% block content %}
    <h4>Thank you. You have just voted on "{{poll.text}}" which has "{{poll.num_votes}}" votes. You chose "{{choice.choice_text}}".</h4>
    <ul>
        {% for choice in poll.choice_set.all %}
        <li>{{choice.choice_text}} - {{choice.num_votes}}</li>
        {% endfor %}
    </ul>
{% endblock %}

poll/templates/poll/polls.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Polls Lists {% endblock%}
{% block font_css %} 
   <script src="https://kit.fontawesome.com/e6b819aa57.js" crossorigin="anonymous"></script>
{% endblock %}
{% block content %} 
<div class="container">
    <a href="?title=True" class="btn btn-{% if 'title' in request.GET %}warning{% else %}primary{% endif %}">A-Z </i></a>

    <a href="?latest=True" class="btn btn-{% if 'latest' in request.GET %}warning{% else %}primary{% endif %}">Latest</a>
    
    <a href="?mine=True" class="btn btn-{% if 'mine' in request.GET %}warning{% else %}primary{% endif %}">My polls</a>
    
    <a href="{% url "poll:add" %}" class="btn btn-primary">Add Poll <i class="fas fa-plus"></i></a>
    <br> <br>
    
    <form class="form-inline my-2 my-lg-2">
      <input class="form-control mr-sm-2" name="search" type="search" value="{{search}}" placeholder="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>

        {% if messages %}
                {% for message in messages %} 
                    <div {% if message.tags %} class="{{message.tags}}" {% endif %}>
                        {{message}}
                    </div>
                {% endfor %}
        {% endif %}
    <ul class="list-group">
        {% for poll in polls %}
        <li class='list-group-item'>
            <a href="{% url 'poll:details' poll.id %}">{{poll}}</a>
            {% if request.user == poll.owner %}         
                <a class="float-right" href="{% url 'poll:edit_poll' poll.id %}"><i class="fas fa-pencil-alt">edit</i> </a>
            {% endif %}
        </li>
        {% endfor %}
    </ul>
    <div class="">
        <span class="">
            {% if polls.has_previous %}
                <a href="?page=1&{{params}}">&laquo; first</a>
                <a href="?page={{ polls.previous_page_number }}&{{params}}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ polls.number }} of {{ polls.paginator.num_pages }}.
            </span>

            {% if polls.has_next %}
                <a href="?page={{ polls.next_page_number }}&{{params}}">next</a>
                <a href="?page={{ polls.paginator.num_pages }}&{{params}}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>
{% endblock %}