accounts/urls.py
from django.urls import path
from accounts import views 
app_name="accounts"

urlpatterns = [
    path('login/',views.loginview,name="login"),
    path('logout/',views.logoutview,name="logout"),
    path('register',views.register,name="register"),
]

poll/urls.py
from django.urls import path,include
from poll import views
from rest_framework.routers import DefaultRouter

app_name="poll"

router=DefaultRouter()
router.register('api/polls',views.PollViewSet,)

urlpatterns = [
    path('',views.polls,name="polls"),
    path('add/',views.add_poll,name="add"),
    
    path('details/',include([
        path('<int:poll_id>/',views.poll_detail,name="details"),
        path('<int:poll_id>/vote/',views.poll_vote,name="vote")
    ])),
    
    path('edit/',include([
        path('poll/<int:poll_id>',views.edit_poll,name="edit_poll"),
        path('<int:poll_id>/choice/add/',views.add_choice,name="add_choice"),
        path('choice/<int:choice_id>',views.edit_choice,name="edit_choice"),
    ])),
    
    path('delete/',include([
        path('choice/<int:choice_id>',views.delete_choice,name="delete_choice"),
        path('poll/<int:poll_id>/',views.delete_poll,name="delete_poll"),
    ])),
    
    # API VIEWS starts
    path('api/',include([
        path('users',views.Users.as_view(),name="users"),
        path('login',views.LoginView.as_view(),name="api_login"),
        path('polls/', include([
            # path('',views.PollList2.as_view(),name="polls_list"),
            # path('<int:pk>',views.PollDetail2.as_view(),name="poll_detail"),
            path('<int:poll_pk>/choices',views.ChoiceList.as_view(),name="choice_list"),
            path('<int:poll_pk>/choices/<int:choice_pk>/vote',views.CreateVote.as_view(),name="create_vote"),
        ]))
    ]))
]

# adds url paths for polls list,create and details views
# first arg on register func tacks on to the app's default url i.e  127.0.0.1:8000/<app_name>/<first_arg>/
# and use base_name for path name ie poll-list,poll-details
urlpatterns+= router.urls 

pollme/urls.py
from django.contrib import admin
from django.urls import path,include
from pollme import views
# from rest_framework_swagger.views import get_swagger_view
from rest_framework.documentation import include_docs_urls
# schema_view = get_swagger_view(title='Polls API')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name="home"),
    path('poll/',include('poll.urls',namespace="poll")),
    path('accounts/',include('accounts.urls',namespace="accounts")),
    # path('swagger-docs/', schema_view),
    path('docs/', include_docs_urls(title='M\'s simple Polls API Build')),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>  {% block title %} Polls {% endblock %} </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% block css %} {% endblock %}
    {% block font_css %} {% endblock %}
</head> 
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'home' %}">Eto idibo</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="#">Ile <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">eto afikun</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "poll:polls" %}">asayan</a>
          </li>
        </ul>
      </div>
      <div class="nav ml-auto">
        <ul class="navbar-nav">
          {% if request.user.is_authenticated %}
          <li class="nav-item"><a href="{% url 'accounts:logout' %}" class="nav-link">Logout</a></li>
          {% else %}
          <li class="nav-item"><a href="{% url 'accounts:login' %}" class="nav-link">Login</a></li>
          <li class="nav-item"><a href="{% url 'accounts:register' %}" class="nav-link">register</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    {% block content%}

    {% endblock %}
  
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block css %}<link rel="stylesheet" href="{% static 'css/style.css' %}"> {% endblock %}
{% block title %} home{% endblock %}
{% block content %} 
<div class="container text-center">
    <div class="row">
        <div class="col">
            <div id="home-content">
                <h1>Get started with polls</h1>
                <h3>Vote for Maleem</h3>
                <hr>
                <button class="btn btn-lg btn-secondary">start!</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}